name: Deploy on master change

on:
  push:
    branches:
      - master

jobs:
  ci:
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }},
    uses: ./.github/workflows/ci.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y ssh-client

    - name: SSH and run commands
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Save private key to a file
        chmod 600 private_key.pem
        # SSH into the remote machine and run the commands
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USERNAME@$HOST "cd pnwx && git pull && git reset --hard && pnpm install && git reset --hard && pnpm run build &&  exit"
