name: Deploy

on:
  workflow_run:
    workflows: ["CI"]  # Replace with the name of your CI workflow
    types:
      - completed
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:


  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH client
      run: sudo apt-get install -y ssh-client
    - name: SSH and run commands
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Save private key to a file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        # SSH into the remote machine and run the commands
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USERNAME@$HOST "cd pnwx && git pull && git reset --hard && pnpm install && git reset --hard && pnpm run build &&  exit"
